### ISSUE TITLE
please cite and link to my work when using my code !

### ISSUE THREAD

**Issue by lclevy** [louisabraham/ffpass#62]
I was the first to write a 100% python tool to decode Mozilla passwords, before everybody was using NSS library
https://github.com/lclevy/firepwd

my code is under GPL, so you can not change it to MIT

at least link to my repository and cite my name !

**Comment by louisabraham** [comment]
Hi, the original version of ffpass was very inspired by your retro engineering, however the code was a full rewrite by me, see https://github.com/louisabraham/ffpass#credits
As stated there, the latest version comes from #55. I didn't check this version for copyright infringement.

Could you tell me whether your concerns are about the previous or the newest version?

**Comment by louisabraham** [comment]
I see two different issues here: using your reverse engineering ideas and your code.

Ideas are not subject to software license AFAIK and I was already crediting you. I'm open to suggestions.

If some code was reused from your repository (I guess from 55, please tell me), it's a bigger problem because I don't want to make ffpass GPL. I guess I can rebase the history to push a GPL license with our both names and then rewrite your code so that this repo can stay MIT. Rebasing is a hassle, would you be ok if I just add a mention in the readme telling that versions in between are subject to GPL and reuse your code?

**Comment by lclevy** [comment]
hi Louis,

thanks you your fast aswer.

ok, I did not see the credits section, sorry. So many people are sealing my code without credits...

I suggest comments in code where portions of my original code remain, such as
code from lines 81 to 168 (main crypto code) is 90% from me:
https://github.com/louisabraham/ffpass/blob/master/ffpass/__init__.py#L81
https://github.com/louisabraham/ffpass/blob/master/ffpass/__init__.py#L168

comments remains when code is forked, which force wrong people to remove it explicitly.

about MIT license, this risk is : some could use your code in commercial product, them a lawer will see later it is based on GPL code and it is illegal. Legally you can not use GPL code in MIT software.

I do not want to be agressive, just avoid other are using my work without proper credits

**Comment by louisabraham** [comment]
No worries, I understand your concern and I am sorry that #55 broke the GPL license, I didn't check for code reuse.

Indeed, the two functions from line 157 to 181 (decrypt3DES and decodeLoginData) are similar to your code, especially the variable names and the comment "first base64 decoding, then ASN1DERdecode". I didn't a lot of similarity in the rest of the code, please correct me if I'm wrong.

I'll rewrite these functions slightly without altering their purpose nor the computation they do, after which the merger doctrine and threshold of originality should apply and free ffpass from the GPL license. We are basically implementing the same algorithm and there isn't a lot of different ways to do it.

Btw, if you want to think about copyrightability, the cryptography part of your code is just a reimplementation of the code that firefox uses. Fortunately, fair use is relevant here. Likewise, I am free to reimplement this code (and not copy it like it was done, probably without any malicious intent, by @lmcclell).

**Comment by lclevy** [comment]
Bonjour Louis,

Of course, the original algorithm is from Mozilla people, but what was difficult and took me days is to understand it and reimplement it in Python, in a simple way. Take a look at NSS code https://hg.mozilla.org/projects/nss, you'll understand what I mean.
What I documented via Python code is where relevant ASN1 data are located, which crypto algorithms to use and how.

You reused all my variable names as is, because they describe data structures and inputs to crypto algorithms.

"I didn't a lot of similarity in the rest of the code, please correct me if I'm wrong."
let's compare more closely, then:

* 3DES decryption
https://github.com/louisabraham/ffpass/blob/58ce333e381676ed78de0b05fba579a18b8e37c7/ffpass/__init__.py#L157
https://github.com/lclevy/firepwd/blob/master/firepwd.py#L161
* AES decryption
https://github.com/louisabraham/ffpass/blob/58ce333e381676ed78de0b05fba579a18b8e37c7/ffpass/__init__.py#L140
https://github.com/lclevy/firepwd/blob/master/firepwd.py#L161
(I documented the b'\x04\x0e' trick, which is a hack from Mozilla devs for compatibility)
* reading key4.db
https://github.com/louisabraham/ffpass/blob/58ce333e381676ed78de0b05fba579a18b8e37c7/ffpass/__init__.py#L82
https://github.com/lclevy/firepwd/blob/master/firepwd.py#L380
same variable names, which proves it is based on my code
* decodeLoginData()
https://github.com/louisabraham/ffpass/blob/58ce333e381676ed78de0b05fba579a18b8e37c7/ffpass/__init__.py#L171
https://github.com/lclevy/firepwd/blob/master/firepwd.py#L176
exact same variabme names again.
code is slightly different, because you added import of passwords, and wrote encodeData

Here is a nice addition to Lazagne
https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L3 

I not sure rewrite of GPL code will allow a MIT licence. Here is a discussion about that : https://stackoverflow.com/questions/3902754/mit-vs-gpl-license

from crypto point of view, only 1 iteration of PBKDF2 is really bad, recommended is 1000
https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf

Laurent

**Comment by louisabraham** [comment]
Just to be clear: I'm not contesting that the code is similar since even my original version used your reverse engineering. I'm also not the one who copied the new functions without any modification (but I'm definitely responsible for merging them).

Thanks for the code pointers. I can reimplement them too if you prefer, else I'll assume it's fine with you.

Again, I **do** recognize the code uses your ideas. It's just that ideas are not subject to software licenses and our codes, given these ideas, are very straightforward.

> Here is a nice addition to Lazagne
How is it nicer than `ffpass`? I'll add a link to your repository in the python file if you want. However you will notice that Lazagne is not GPL either, it's LGPL and they also did not include any copyright notice for your code.

> from crypto point of view, only 1 iteration of PBKDF2 is really bad, recommended is 1000
Agreed! But I don't see how it's related to our discussion?

**Comment by louisabraham** [comment]
Here, I added a link to your code. Personally I think the README makes you more visible, you should ask LaZagne to do the same!
